CREATE DOMAIN u64 AS int8 CHECK ( VALUE >= 0 AND VALUE < 18446744073709551616);

CREATE TABLE teleinfo (
    id SERIAL PRIMARY KEY NOT NULL,
    dt_utc TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    adco VARCHAR(12) NOT NULL,
    hcjb u64 NOT NULL,
    hpjb u64 NOT NULL,
    hcjw u64 NOT NULL,
    hpjw u64 NOT NULL,
    hcjr u64 NOT NULL,
    hpjr u64 NOT NULL
);

